importScripts(
  "avatar-cache.js",
  "highlighted-pages-worker.js",
  "service-worker.js",
  "github-split-view.js",
  "github-app-auth.js",
  "youtube-search-worker.js",
  "research-publisher-background.js",
  "research-launcher-background.js"
);
